# Generated by Django 3.2.5 on 2021-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=5)),
                ('name_Book', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=150)),
                ('ISBN', models.CharField(max_length=25)),
                ('Image', models.ImageField(upload_to='photoes/%y/%m/%d')),
                ('pages', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
