# Generated by Django 3.2.5 on 2021-07-15 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
                ('date_of_login', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_book', to='Book.book')),
            ],
        ),
    ]
