# Generated by Django 3.2.5 on 2021-07-18 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_alter_book_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 18, 21, 38, 35, 645400, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
