# Generated by Django 3.2.5 on 2021-07-19 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_remove_profile_book_vaforite'),
        ('Book', '0005_alter_book_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.profile'),
        ),
    ]
