# Generated by Django 3.2.5 on 2021-07-17 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
                ('date_of_login', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=50)),
                ('userprofile', models.ImageField(upload_to='photoes/%y/%m/%d')),
                ('Book_vaforite', models.ManyToManyField(to='Book.Book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
