# Generated by Django 3.2.5 on 2021-07-15 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersname',
            name='id',
        ),
        migrations.AddField(
            model_name='usersname',
            name='UserName',
            field=models.CharField(default=django.utils.timezone.now, max_length=25, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
