# Generated by Django 3.2.5 on 2021-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userprofile',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
