# Generated by Django 3.2.5 on 2021-07-15 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20210715_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersname',
            name='Email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersname',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersname',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
