# Generated by Django 3.2.5 on 2021-07-15 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_auto_20210715_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersname',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
