# Generated by Django 3.2.5 on 2021-07-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_alter_profile_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Book_vaforite',
        ),
    ]
